### ISSUE TITLE
Local scopes of loops?

### ISSUE THREAD

**Issue by lucifer1004** [dannyvankooten/monkey-c-monkey-do#1]
Your implementation is the fastest I've ever seen among all Monkey implementations. Quite impressive.

I am also a Monkey developer (in Julia, see https://github.com/lucifer1004/MonkeyLang.jl), and I am also trying to extend Monkey features. 

One feature I have implemented is the `while` loop. I want that the loops can have their own local scopes, which increases the complexity (a new type of scope, a few new opcodes). I see that your implementation does not create new scopes for loops, but I wonder your opinion on how to implement local scopes for loops, regarding your great knowledge of compilers reflected in the performance improvements you have made in this project.

**Comment by dannyvankooten** [comment]
Hey @lucifer1004,

Thank you!

To be brutally honest I don't think I have that much of value to share with you. The performance of my implementation is mostly about two things:

- Making sure no system calls for memory allocation have to occur during runtime, so everything is pre-allocated (or at least a large enough memory pool is).
- Manually inlining some hot paths using macro's (very minor).
- Optimizing the object representation so more objects fit in CPU registers.

[dannyvankooten/pepper-lang](https://github.com/dannyvankooten/pepper-lang) is a more complete continuation of what I have in this repository by the way, but it is still not supporting local scopes for loops so may not be all that helpful. Sorry..
